library(targets)
library(tarchetypes)
library(here)

source(here("R", "functions.R"))
source(here("R", "load_data.R"))
source(here("R", "utils.R"))
source(here("R", "regression.R"))

tar_option_set(packages = c("dplyr", "DBI", "RPostgres"))

list(
  tar_target(
    raw_data,
    load_data()
  ),
  tar_target(
    summary_data,
    summarise_data(raw_data)
  ),
  tar_target(
    summary_casualty_sex,
    summarise_casualty_sex(raw_data)
  ),
  tar_render(
    report,
    "vignettes/Report.Rmd"
  ),
  tar_target(
    pre_bike_hire,
    load_bike_hire_data()
  ),
  tar_target(
    bike_hire,
    create_dtg(pre_bike_hire)
  ),
  tar_target(
    simpletrend,
    plot_simpletrend(bike_hire)
  ),
  tar_target(
    temphire,
    plot_temphire(bike_hire)
  ),
  tar_target(
    weekday,
    plot_weekday(bike_hire)
  ),
  tar_target(
    season,
    plot_season(bike_hire)
  ),
  tar_target(
    humidity_windspeed,
    plot_humidity_windspeed(bike_hire)
  ),
  tar_target(
    simple_gam,
    fit_simple_gam(bike_hire)
  ),
  tar_target(
    final_gam,
    fit_final_gam(bike_hire)
  ),
  tar_target(
    insurance,
    get_insurance_data()
  ),
  tar_target(
    claims,
    plot_claims(insurance)
  ),
  tar_target(
    claim_rate,
    plot_claim_rate(insurance)
  ),
  tar_target(
    fit_offset_model,
    fit_glm_with_offset(insurance)
  ),
  tar_target(
    helprct,
    get_helprct()
  ),
  tar_target(
    mh_model,
    fit_mh_score(helprct)
  ),
  tar_render(
    regression_report,
    "vignettes/regression.Rmd"
  )
)
