name: olive_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - jupyter
  - pyyaml
  - quarto
  - scikit-learn
  - matplotlib
  - pytest
  - pip
  - pip:
    - doit
